version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /application/certificate/test.samanii.com.cer:/application/certificate/test.samanii.com.cer
      - /application/certificate/test.samanii.com.cer.key:/application/certificate/test.samanii.com.cer.key
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - nginx-network

  telegram_db:
      container_name: telegram_db
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data

  api:
    expose:
      - 5000
    restart: unless-stopped
    user: root
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - 5000:5000
    networks:
      - nginx-network
    volumes:
      - ./images:/app/wwwroot/images
      - /log:/app/log-*.json
    depends_on:
      - sqlserver
      - telegram_db

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "Hossein8916"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data/sqlserver:/var/opt/mssql/data
    restart: unless-stopped
    networks:
      - nginx-network
  
