version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/test.samanii.com/fullchain.pem:/etc/letsencrypt/live/test.samanii.com/fullchain.pem
      - /etc/letsencrypt/live/test.samanii.com/privkey.pem:/etc/letsencrypt/live/test.samanii.com/privkey.pem
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - nginx-network

  api:
    expose:
      - 5000
    restart: unless-stopped
    user: root
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - 5000:5000
    networks:
      - nginx-network
    volumes:
      - images-volume:/app/wwwroot/images
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "Hossein8916"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    restart: unless-stopped
    networks:
      - nginx-network
  
