version: '3.4'

services:
  telegram_db:
    image: redis:alpine
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest

  nginx:
    image: nginx:stable-alpine

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: src/digitall/Api/Dockerfile

networks:
  nginx-network:
    driver: bridge

volumes:
  sqlserver-data:
    driver: local
  images-volume:
  log-volume:  
  