version: '3.4'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - nginx-network

  api:
    expose:
      - 5000
    restart: unless-stopped
    environment:
      - ASPNETCORE_HTTP_PORTS=5000
    ports:
      - 5000:5000
    networks:
      - nginx-network
    volumes:
      - ./digitall/Api/bin/Debug/net8.0/.xml:/app/Digitall.Api.XML
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Hossein8916"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql/data
      - ./src/sqlserver/restore_script.sql:/docker-entrypoint-initdb.d/restore_script.sql
    restart: unless-stopped
    networks:
      - nginx-network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h; done'"
