name: deploay when change bot server

on:
  push:
    branches:
      - change-server

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_NEW_IP }}
          username: ${{ secrets.SERVER_NEW_USER }}
          key: ${{ secrets.SERVER_NEW_SSH_KEY }}
          debug: true
          script: |
            cd /application/digitall.microservice
            git pull
