name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: pulling changes for server
      run: ssh -i hossein_rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDbUsRH3LxLTE+HOKkDvQTbc4qFTPPZiWooAekTn6oS7qPlEGvOrxIgcwtAX2drGAAUes5Z7Cpani6luwl7OMssWyDy1wRI2xxrjOLF4ifFE8vhJ0yiIf8TRfRRE54g3dMUB/qQ+na4i7Hc5VOS31m4K1J2n4Ewr1s4rKW0xzTEtPjOFRtJrqqjjaeqFojAFE8EE25JhvhOyTpaW2Bh7D/gtbRJ6QkphZe49NdmFZDSTKpEvIn+B8UnDHO2Gp8ZCh855wxD0Ka4A93tf0lsiJw8mpGJ8KBvg1PGIGcg4sH0qbnYCc0RzNn2jJOUhxYmUAp2kmovKGPYGA3b8dwG8IGRF2NcD/asICTkuKynakhOcIypXpIicFE/btTjDKJ3mRzXJgYbvqtr8mAwCpk0Oz+V89OtpnkRTLzrMDuL4llgZmXF/HoUdk9w+h/SL5GcwISY7UClmXyay6z/32nIHas++tp628hcmBr2LAc+LF+fkHLoMbFF8xlrabMlQfz+xHvNp9vJpawYQvVewG9nmYkeITTU2KbDIA7EyBVIUo5LN68k5G0e6jXgxWviOKvLm+R1d7RxY7puYcDn5XPv9bXBuXcuLnh/s0Kh3AKSh6FDh4LM7TXbKY6l6lvmGs/EOPWGxHxUYBKgVZl2j0VyiuigcoiYVQzNj93Ogzsyb2y63w== h.faraji8079@gmail.com root@95.179.199.192 'ls'
    
    # - name: pulling changes for server
    #   run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'ls'
    
    # - name: Load Docker image on server
    #   run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'docker load -i ~/my-app.tar'

    # - name: Run Docker container on server
    #   run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'docker run -d --name my-app-container -p 80:80 my-app'
