name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t my-app .

    - name: Save Docker image to a tar file
      run: docker save my-app -o my-app.tar

    - name: Copy Docker image to server
      uses: appleboy/scp-action@v0.1.1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "my-app.tar"
        target: "~/my-app.tar"

    - name: Load Docker image on server
      run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'docker load -i ~/my-app.tar'

    - name: Run Docker container on server
      run: ssh -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'docker run -d --name my-app-container -p 80:80 my-app'
